server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # PROXY REVERSO: Bloqueia a porta do Backend na AWS e absorve a carga pela Porta 80
    # O React vai chamar coisas como /api/financeiro, e o Nginx manda para backend:3000/financeiro
    location /api/ {
        proxy_pass http://backend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Essa configuração garante que acessar links como /obras/1 não retorne ERRO 404.
    # O Nginx redireciona tudo para o index.html, e o React Router assume o controle da navegação.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
