server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Essa configuração garante que acessar links como /obras/1 não retorne ERRO 404.
    # O Nginx redireciona tudo para o index.html, e o React Router assume o controle da navegação.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
